version: '3'

services:
  database:
    image: drupaldocker/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: meh
    ports:
      - "9906:3306"
  web:
    image: drupaldocker/php:7.2-apache
    container_name: php_web
    links:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true